### ISSUE TITLE
readBean() needs javadocs on EOF handling

### ISSUE THREAD

**Issue by j256** [42BV/CSVeed#52]
Right now BeanReader.readBean() and CsvClient.readBean() don't have any information about how to detect EOF.  Should be:

```
 @return Bean read from the reader or null on EOF.
```

Thanks.

**Comment by hazendaz** [comment]
closing as duplicate of javadoc issues on https://github.com/42BV/CSVeed/issues/50.  Will be looking at all and will review this again as it will now be linked.
