### ISSUE TITLE
Default separator for CSV library is semi-colon?

### ISSUE THREAD

**Issue by j256** [42BV/CSVeed#54]
Just a comment really but a library with Comma Separated Values in its name choosing to make semi-colon the default separator is really strange.  Being able to set the separator is laudable of course but I'd like to vote [strongly] for the default to be ','.

**Comment by davidmc24** [comment]
:+1:

**Comment by manish-in-java** [comment]
:+1:

**Comment by hazendaz** [comment]
closing as duplicate of https://github.com/42BV/CSVeed/issues/81
