### ISSUE TITLE
Update "Comparison matrix" page

### ISSUE THREAD

**Issue by ZioberMichal** [42BV/CSVeed#65]
Hi,
   I could not find project on GitHub where [Comparison matrix](http://csveed.org/comparison-matrix.html) is maintained so I decided to create issue in this project. Please, let me know if it is not the best place for it.

I have released new version of "Super CSV" project where we fixed some bugs and added new functionality. Could you please update information about this project on this page?

| Row name | New row value | Description |
| --- | --- | --- |
| Version | 2.4.0 | [See this page](https://github.com/super-csv/super-csv/releases) |
| Last updated | 29.10.2015 | [See this page](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22net.sf.supercsv%22) |
| custom EOL | yes | [See test "testCustomEOL" in this class](https://github.com/super-csv/super-csv/blob/master/super-csv/src/test/java/org/supercsv/features/ReadingFeaturesTest.java) |
| deal with leading/trailing whitespace | yes | [See test "testDealWithLeadingTrailingWhitespace" in this class](https://github.com/super-csv/super-csv/blob/master/super-csv/src/test/java/org/supercsv/features/ReadingFeaturesTest.java) |
| get by column name | yes | [See test "testGetByColumnName" in this class](https://github.com/super-csv/super-csv/blob/master/super-csv/src/test/java/org/supercsv/features/ReadingFeaturesTest.java) |
| skip comment lines | yes | [See test "testSkipCommentLines" in this class](https://github.com/super-csv/super-csv/blob/master/super-csv/src/test/java/org/supercsv/features/ReadingFeaturesTest.java) |
| Converter support | yes | [See test "testConverterSupport" in this class](https://github.com/super-csv/super-csv/blob/master/super-csv/src/test/java/org/supercsv/features/ReadingFeaturesTest.java) |

**Comment by hazendaz** [comment]
See https://github.com/42BV/CSVeed/pull/175

I've only updated websites and few of the various items around versions and dates.  Will try to do more and sure in last decade there are probably more around.
